name: grizzly_distuv
description: Statistics and probability library for Dart
version: 0.2.0-dev
homepage: https://github.com/Grizzly-dart/grizzly_stats
author: Ravi Teja Gudapati <tejainece@gmail.com>

environment:
  sdk: '>=2.1.0 <3.0.0'

dependencies:
  grizzly_range: ^2.0.6

dev_dependencies:
  test:
  # grizzly_scales:
  # grizzly_primitives:
  grizzly_array:
    path: ../grizzly_array
  # grizzly_series:
  #grizzly_series:
  #  path: ../grizzly_series
  #grizzly_scales:
  #  path: ../grizzly_scales
